# Generated by Django 4.0.2 on 2022-03-13 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_quiz_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 16, 11, 30, 607144, tzinfo=utc), verbose_name='date_published'),
        ),
    ]
